// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.msk1;
using System.Collections.Generic;

namespace SeriesEngine.Core
{
	public static class ModelsDescription
	{
        public static IEnumerable<MetaModel> All
        {
            get
            {
                yield return msk1;
            }
        }

        public static MetaModel msk1 = new MetaModel
        {
            Name = "msk1",
            ObjectModels = msk1Objects.UsedObjects,
			HierarchyModels = msk1Hierarchies.UsedHierarchies
        };
	}
}
