// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using SeriesEngine.Core;

namespace SeriesEngine.msk1
{
	public class msk1SupplierVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
                yield break;
            }
        }
	}
}
