// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using SeriesEngine.Core.DataAccess;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SeriesEngine.msk1
{

    [Table("msk1.ElectricMeter_Integrals")]
    public partial class ElectricMeter_Integral : PeriodVariable
    {
        [Required]
        //[StringLength(200)]
        public Double Integral { get; set; }

        public virtual ElectricMeter ElectricMeter { get; set; }

        public override object Value
        {
            get
            {
                return Integral;
            }
            set
            {
                Integral = (Double)value;
            }
        }
    }
}
