// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using SeriesEngine.Core.DataAccess;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;


namespace SeriesEngine.msk1
{
    [Table("msk1.SupplierHierarchyNodes")]
    public partial class SupplierHierarchyNode : NetworkTreeNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierHierarchyNode()
        {
            Children = new HashSet<SupplierHierarchyNode>();
        }

        public int NetId { get; set; }
        [ForeignKey("NetId")]
        public virtual SupplierHierarchyNetwork Network { get; set; }

        public override Network MyNetwork
        {
            get
            {
                return Network;
            }
            set
            {
                Network = (SupplierHierarchyNetwork)value;
            }
        }

        public override NetworkTreeNode MyParent
        {
            get
            {
                if (Parent == null)
                {
                    return null;
                }
                return Parent.LinkedObject != null ? Parent : Parent.MyParent;
            }
            set
            {
                Parent = (SupplierHierarchyNode)value;
            }
        }

        public int? ParentId { get; set; }

        public virtual SupplierHierarchyNode Parent { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierHierarchyNode> Children { get; set; }

		public int? Tag { get; set; }


        public int? Supplier_Id { get; set; }
        public virtual Supplier Supplier { get; set; }

        public int? SupplierContract_Id { get; set; }
        public virtual SupplierContract SupplierContract { get; set; }

        public int? Point_Id { get; set; }
        public virtual Point Point { get; set; }

        public override NamedObject LinkedObject
        {
            get
            {
                if (Supplier != null)
                {
                    return Supplier;
                }
                if (SupplierContract != null)
                {
                    return SupplierContract;
                }
                if (Point != null)
                {
                    return Point;
                }
                return null;
            }
        }
	}
}

