// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using SeriesEngine.Core;

namespace SeriesEngine.msk1
{
	public class msk1PointVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return VoltageLevel;
				yield return MaxPower;
				yield return TUCode;
				yield return BPGroup;
				yield return PUPlace;
				yield return ContractPriceCategory;
            }
        }

		public static Variable VoltageLevel = new Variable(Point.VoltageLevelParser)
        {
			Name = "VoltageLevel",
			IsPeriodic = true,
			IsVersioned = true,
			ValueType = typeof(String),
			EntityType = typeof(Point_VoltageLevel)
		};

		public static Variable MaxPower = new Variable(Point.MaxPowerParser)
        {
			Name = "MaxPower",
			IsPeriodic = true,
			IsVersioned = true,
			ValueType = typeof(Double),
			EntityType = typeof(Point_MaxPower)
		};

		public static Variable TUCode = new Variable(Point.TUCodeParser)
        {
			Name = "TUCode",
			IsPeriodic = true,
			IsVersioned = true,
			ValueType = typeof(String),
			EntityType = typeof(Point_TUCode)
		};

		public static Variable BPGroup = new Variable(Point.BPGroupParser)
        {
			Name = "BPGroup",
			IsPeriodic = true,
			IsVersioned = true,
			ValueType = typeof(String),
			EntityType = typeof(Point_BPGroup)
		};

		public static Variable PUPlace = new Variable(Point.PUPlaceParser)
        {
			Name = "PUPlace",
			IsPeriodic = false,
			IsVersioned = true,
			ValueType = typeof(String),
		};

		public static Variable ContractPriceCategory = new Variable(Point.ContractPriceCategoryParser)
        {
			Name = "ContractPriceCategory",
			IsPeriodic = false,
			IsVersioned = true,
			ValueType = typeof(String),
		};
	}
}
