// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using System.Collections.Generic;

namespace SeriesEngine.msk1
{
	public class msk1ElectricMeterVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return PUType;
				yield return HourCount;
				yield return Class;
				yield return Direction;
				yield return Integral;
            }
        }

		public static Variable PUType = new Variable(ElectricMeter.PUTypeSetter)
        {
			Name = "PUType",
			IsPeriodic = false,
			IsVersioned = false,
		};

		public static Variable HourCount = new Variable(ElectricMeter.HourCountSetter)
        {
			Name = "HourCount",
			IsPeriodic = false,
			IsVersioned = false,
		};

		public static Variable Class = new Variable(ElectricMeter.ClassSetter)
        {
			Name = "Class",
			IsPeriodic = false,
			IsVersioned = false,
		};

		public static Variable Direction = new Variable(ElectricMeter.DirectionSetter)
        {
			Name = "Direction",
			IsPeriodic = false,
			IsVersioned = true,
		};

		public static Variable Integral = new Variable(ElectricMeter.IntegralSetter)
        {
			Name = "Integral",
			IsPeriodic = true,
			IsVersioned = true,
			EntityType = typeof(ElectricMeter_Integral)
		};
	}
}
