// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using SeriesEngine.Core;

namespace SeriesEngine.msk1
{
	public class msk1ContractVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return ContractType;
            }
        }

		public static Variable ContractType = new Variable(Contract.ContractTypeParser)
        {
			Name = "ContractType",
			IsPeriodic = false,
			IsVersioned = false,
			ValueType = typeof(String),
		};
	}
}
