// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using System.Collections.Generic;

namespace SeriesEngine.msk1
{
	public class msk1ContractVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return Name;
				yield return ContractType;
            }
        }

		public static Variable Name = new Variable
        {
			Name = "Name",
			IsPeriodic = false,
			IsVersioned = false
		};
		public static Variable ContractType = new Variable
        {
			Name = "ContractType",
			IsPeriodic = false,
			IsVersioned = false
		};
	}
}
