// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using System.Collections.Generic;

namespace SeriesEngine.msk1
{
    public static class msk1Hierarchies
    {
        public static IEnumerable<HierarchyMemamodel> UsedHierarchies
        {
			get
			{
				yield return MainHierarchy;
				yield return SupplierHierarchy;
			}
		}

        public static HierarchyMemamodel MainHierarchy = new HierarchyMemamodel
        {
            Name = "MainHierarchy",
            ReferencedObjects = new [] 
			{
				msk1Objects.Region,
				msk1Objects.Consumer,
				msk1Objects.Contract,
				msk1Objects.ConsumerObject,
				msk1Objects.Point,
				msk1Objects.ElectricMeter,
			},
			NodeType = typeof(SeriesEngine.msk1.MainHierarchyNode)
        };

        public static HierarchyMemamodel SupplierHierarchy = new HierarchyMemamodel
        {
            Name = "SupplierHierarchy",
            ReferencedObjects = new [] 
			{
				msk1Objects.Supplier,
				msk1Objects.SupplierContract,
				msk1Objects.Point,
			},
			NodeType = typeof(SeriesEngine.msk1.SupplierHierarchyNode)
        };
	}
}
