// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using System.Collections.Generic;

namespace SeriesEngine.msk1
{
	public class msk1PointVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return Name;
				yield return VoltageLevel;
				yield return MaxPower;
				yield return TUCode;
				yield return PUPlace;
            }
        }

		public static Variable Name = new Variable
        {
			Name = "Name",
		};
		public static Variable VoltageLevel = new Variable
        {
			Name = "VoltageLevel",
		};
		public static Variable MaxPower = new Variable
        {
			Name = "MaxPower",
		};
		public static Variable TUCode = new Variable
        {
			Name = "TUCode",
		};
		public static Variable PUPlace = new Variable
        {
			Name = "PUPlace",
		};
	}
}
