// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using SeriesEngine.Core.DataAccess;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SeriesEngine.msk1
{
    [Table("msk1.Points")]
	public partial class Point : NamedObject
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Point() : base(msk1Objects.Point)
        {
			Point_VoltageLevels = new HashSet<Point_VoltageLevel>();
			Point_MaxPowers = new HashSet<Point_MaxPower>();
			Point_TUCodes = new HashSet<Point_TUCode>();
			Point_BPGroups = new HashSet<Point_BPGroup>();
			Point_PUPlaces = new HashSet<Point_PUPlace>();
			Point_ContractPriceCategorys = new HashSet<Point_ContractPriceCategory>();
		}

        public override string GetName()
        {
            return Name;
        }

        public override void SetName(string newName)
        {
            Name = newName;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_VoltageLevel> Point_VoltageLevels { get; set; }
		public static bool VoltageLevelSetter(NamedObject obj, string value) 
		{
			var target = (Point)obj;
			return false;
		}

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_MaxPower> Point_MaxPowers { get; set; }
		public static bool MaxPowerSetter(NamedObject obj, string value) 
		{
			var target = (Point)obj;
			return false;
		}

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_TUCode> Point_TUCodes { get; set; }
		public static bool TUCodeSetter(NamedObject obj, string value) 
		{
			var target = (Point)obj;
			return false;
		}

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_BPGroup> Point_BPGroups { get; set; }
		public static bool BPGroupSetter(NamedObject obj, string value) 
		{
			var target = (Point)obj;
			return false;
		}

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_PUPlace> Point_PUPlaces { get; set; }
		public static bool PUPlaceSetter(NamedObject obj, string value) 
		{
			var target = (Point)obj;
			return false;
		}

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_ContractPriceCategory> Point_ContractPriceCategorys { get; set; }
		public static bool ContractPriceCategorySetter(NamedObject obj, string value) 
		{
			var target = (Point)obj;
			return false;
		}
	}
}
