// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using SeriesEngine.Core.DataAccess;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SeriesEngine.msk1
{
    [Table("msk1.ElectricMeters")]
	public partial class ElectricMeter : NamedObject
	{
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectricMeter() : base(msk1Objects.ElectricMeter)
        {
		}

        public override string GetName()
        {
            return Name;
        }

        public override void SetName(string newName)
        {
            Name = newName;
        }
	
        [Required]
        //[StringLength(int.MaxValue)]
        //[MaxLength]
        public String PUType { get; set; }
	
        [Required]
        //[StringLength(int.MaxValue)]
        //[MaxLength]
        public Boolean HourCount { get; set; }
	
        [Required]
        //[StringLength(int.MaxValue)]
        //[MaxLength]
        public String Class { get; set; }
	}
}
