// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using System.Collections.Generic;

namespace SeriesEngine.test1
{
	public class test1ObjectBVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return Name;
				yield return Description;
            }
        }

		public static Variable Name = new Variable
        {
			Name = "Name",
		};
		public static Variable Description = new Variable
        {
			Name = "Description",
		};
	}
}
