// <autogenerated>
//   This file was generated by T4 code generator BuildMetamodels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using SeriesEngine.Core;
using System.Collections.Generic;

namespace SeriesEngine.test1
{
	public class test1ObjectAVariables
	{
        public static IEnumerable<Variable> AllVariables
        {
            get
            {
				yield return Name;
				yield return Description;
				yield return EnumVariable1;
				yield return EnumVariable2;
				yield return PeriodIntVariable;
				yield return PeriodSmallIntVariable;
				yield return PeriodDecimalVariable;
				yield return PeriodEnumVariable;
            }
        }

		public static Variable Name = new Variable
        {
			Name = "Name",
		};
		public static Variable Description = new Variable
        {
			Name = "Description",
		};
		public static Variable EnumVariable1 = new Variable
        {
			Name = "EnumVariable1",
		};
		public static Variable EnumVariable2 = new Variable
        {
			Name = "EnumVariable2",
		};
		public static Variable PeriodIntVariable = new Variable
        {
			Name = "PeriodIntVariable",
		};
		public static Variable PeriodSmallIntVariable = new Variable
        {
			Name = "PeriodSmallIntVariable",
		};
		public static Variable PeriodDecimalVariable = new Variable
        {
			Name = "PeriodDecimalVariable",
		};
		public static Variable PeriodEnumVariable = new Variable
        {
			Name = "PeriodEnumVariable",
		};
	}
}
